default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "smart_resume") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

development:
  <<: *default
  database: smart_resume_development

test:
  <<: *default
  database: smart_resume_test

production:
  <<: *default
  database: smart_resume_production
  username: smart_resume
  password: <%= ENV["SMART_RESUME_DATABASE_PASSWORD"] %>
